package controller;

public enum ActionsE {
	
	CUADRADOS_MEDIOS,
	CONGRUENCIA_LINEAL,
	CONGRUENCIA_MULTIPLICATIVA,
	DISTRO_UNIFORME,
	DISTRO_NORMAL_EST,
	ABOUT,
	CALCULATE_CONGRUENCIA_MULTIPLICATIVA,
	CALCULATE_DISTRO_UNIFORME
}